interface Diary {
    [key: string | number]: any;
    id: string | number; //not too sure if in the future, id's will be generated by UUID
    name: string;
    visibility: string;
    created_at: string;
}

export default Diary;