interface Memory {
    id: string | number; //not too sure if in the future, id's will be generated by UUID 
    user_id: string; //author 
    title:string;
    content: string;
    visibility: string;
    created_at : string; 
    updated_at: string;
    diary_id: string | number; //not too sure if in the future, id's will be generated by UUID
    diary_name?: string; //optional, sometimes for redundancy
}

export default Memory;