interface Memory {
    id: string | number; //not too sure if in the future, id's will be generated by UUID 

    user_id: string; //author's id
    user_alias?: string; //author's alias
    user_name?: string //author's name

    title:string;
    content: string;
    visibility: string;
    created_at : string; 
    updated_at: string;
    
    diary_id: string | number; //not too sure if in the future, id's will be generated by UUID
    diary_name?: string; //optional, sometimes for redundancy

    /**If a memory is meant to be written as a reply, this property should 
     * contain the target memory which the memory is replying to.
     */
    reply_to_memory_id? : string | number; 
}

export default Memory;