interface Memory {
    id: string | number; //not too sure if in the future, id's will be generated by UUID 
    author: string;
    title:string;
    content: string;
    visibility: string;
    dateTime : string; 
    diaryID: string | number; //not too sure if in the future, id's will be generated by UUID
}

export default Memory;